name: stable-diffusion-modelsscope

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.x # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64 # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
      - name: Install dependencies
        run: pdm install
      - name: Run app.py
        env:
          MODELSCOPE_TOKEN: ${{ secrets.MODELSCOPE_TOKEN }}
        run: |
          python app.py
